CREATE TABLE IF NOT EXISTS silver_std_pitching (
    id TEXT PRIMARY KEY,
    name TEXT,
    team TEXT,
    w_percentile INT,
    l_percentile INT,
    era_percentile INT,
    g_percentile INT,
    gs_percentile INT,
    cg_percentile INT,
    sho_percentile INT,
    sv_percentile INT,
    ip_percentile INT,
    tbf_percentile INT,
    h_percentile INT,
    r_percentile INT,
    er_percentile INT,
    hr_percentile INT,
    bb_percentile INT,
    hbp_percentile INT,
    wp_percentile INT,
    bk_percentile INT,
    so_percentile INT
)