CREATE TABLE IF NOT EXISTS silver_std_batting (
    id TEXT PRIMARY KEY,
    name TEXT,
    team TEXT,
    g_percentile INT,
    ab_percentile INT,
    pa_percentile INT,
    h_percentile INT,
    _1b_percentile INT,
    _2b_percentile INT,
    _3b_percentile INT,
    hr_percentile INT,
    r_percentile INT,
    rbi_percentile INT,
    bb_percentile INT,
    so_percentile INT,
    hbp_percentile INT,
    sf_percentile INT,
    sh_percentile INT,
    gdp_percentile INT,
    sb_percentile INT,
    cs_percentile INT,
    avg_percentile INT
)
